// <auto-generated />
using ChangHeWebSite.Areas.Admin.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChangHeWebSite.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20190117032628_初始化数据库")]
    partial class 初始化数据库
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChangHeWebSite.Areas.Admin.Models.CompanyInfo", b =>
                {
                    b.Property<string>("CompanyName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyCopyright");

                    b.Property<string>("CompanyDescription");

                    b.Property<string>("CompanyEmail");

                    b.Property<string>("CompanyLocation");

                    b.Property<string>("CompanyLogo");

                    b.Property<string>("CompanyPhone");

                    b.Property<string>("CompanyQRcode");

                    b.HasKey("CompanyName");

                    b.ToTable("CompanyInfo");
                });

            modelBuilder.Entity("ChangHeWebSite.Areas.Admin.Models.Navigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NavigationName");

                    b.HasKey("Id");

                    b.ToTable("Navigation");
                });

            modelBuilder.Entity("ChangHeWebSite.Areas.Admin.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NewsClassification");

                    b.Property<string>("NewsContent");

                    b.Property<string>("NewsTitle");

                    b.HasKey("Id");

                    b.HasIndex("NewsClassification");

                    b.ToTable("News");
                });

            modelBuilder.Entity("ChangHeWebSite.Areas.Admin.Models.NewsClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NewsClassificationName");

                    b.HasKey("Id");

                    b.ToTable("NewsClassification");
                });

            modelBuilder.Entity("ChangHeWebSite.Areas.Admin.Models.SystemInfo", b =>
                {
                    b.Property<string>("SystemName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SystemCopyright");

                    b.Property<string>("SystemDescription");

                    b.Property<string>("SystemLogo");

                    b.HasKey("SystemName");

                    b.ToTable("SystemInfo");
                });

            modelBuilder.Entity("ChangHeWebSite.Areas.Admin.Models.News", b =>
                {
                    b.HasOne("ChangHeWebSite.Areas.Admin.Models.NewsClassification")
                        .WithMany("Newses")
                        .HasForeignKey("NewsClassification")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
